### PR TITLE
broker: without automatic PMTU, tell client about static PMTU

### PR DESCRIPTION
**Pull request by RalfJung**
this informs the client about our MTU so both sides use the same

### CODE REVIEW

**Comment by RalfJung** [comment]
@kaechele what do you think about this? How do you handle MTUs in your network?

**Comment by mitar** [comment]
Why would automatic PMTU not work?

**Comment by mitar** [comment]
So Tunneldigger has a custom implementation.

**Comment by RalfJung** [comment]
We talked about this a while ago in https://github.com/wlanslovenija/tunneldigger/issues/62. Note that tunneldigger already has support for disabling auto-PMTU, this just improves that support.

I also think that for our use-case, automatic PMTU is rather useless: we are running a batman mesh network on top of tunneldigger, and the entire mesh is a single layer 2 domain. This means the entire mesh needs to have a single MTU. I do not see how determining precisely the MTU of each tunnel is useful when on top of that tunnel, we anyway need to work with a single MTU that works for everyone. That's why we statically configure a suitably small tunneldigger MTU in our network, which seems to work.

**Comment by mitar** [comment]
I see. Thanks.

**Comment by RalfJung** [comment]
All right, merging then. We've been using this in production for a few weeks now.

**Pull request merged**
