### PR TITLE
Add cmake for client

### PR DESCRIPTION
**Pull request by kaechele**
Here's the client with cmake instead of autotools. Overall a lot cleaner ;-)
Tested on:
- Fedora 27 (x86_64)
- TP-Link Archer C25v1 (LEDE master bc50a97dfc9f6bf3c1c9d0abc56d8ae56b5d48a1)

### CODE REVIEW

**Comment by kaechele** [comment]
LEDE Package Makefile needs to look like this:
```
include $(TOPDIR)/rules.mk

PKG_NAME:=tunneldigger
PKG_VERSION:=0.4.8
PKG_RELEASE:=1
PKG_REV:=c0c74d507818c3b3ea9bb8fe1c277b8a486f5ad9

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.bz2
PKG_SOURCE_URL:=file:///home/felix/Development/tunneldigger
PKG_SOURCE_PROTO:=git
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
PKG_SOURCE_VERSION:=$(PKG_REV)

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/cmake.mk

define Package/tunneldigger
  SECTION:=net
  CATEGORY:=Network
  DEPENDS:=+libnl-tiny +kmod-l2tp +kmod-l2tp-ip +kmod-l2tp-eth +librt +libpthread
  TITLE:=L2TPv3 tunnel broker client
endef

define Build/Prepare
	$(call Build/Prepare/Default)
	mv $(PKG_BUILD_DIR)/client/* $(PKG_BUILD_DIR)
endef

define Package/tunneldigger/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/l2tp_client $(1)/usr/bin/tunneldigger
	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_BIN) ./files/tunneldigger.init $(1)/etc/init.d/tunneldigger
	$(INSTALL_DIR) $(1)/etc/config
	$(INSTALL_DATA) ./files/config.default $(1)/etc/config/tunneldigger
endef

define Package/tunneldigger/conffiles
/etc/config/tunneldigger
endef

$(eval $(call BuildPackage,tunneldigger))
```

**Comment by kostko** [comment]
Nice, this is great, thanks!

**Comment by RalfJung** [comment]
This broke the gluon tunneldigger package at <https://github.com/freifunk-gluon/packages/tree/master/net/tunneldigger>. Do you have an updated version of that somewhere?

**Comment by kaechele** [comment]
I've edited the above makefile to actually reflect the correct commit and repo URL. It should work in gluon as-is.

Here's a patch you can drop in `patches/packages/gluon/0001-Update-to-latest-tunneldigger-master.patch`

```
From: Felix Kaechele <felix@kaechele.ca>
Date: Wed, 22 Nov 2017 22:54:49 +0100
Subject: Update to latest tunneldigger master

Contains fix for the unique session ID problem

Signed-off-by: Felix Kaechele <felix@kaechele.ca>

diff --git a/net/tunneldigger/Makefile b/net/tunneldigger/Makefile
index a57873d38ac9525b2c892885ff03da4b9c2e613a..724109274ad57459ee09d8919383817e1e1d1f39 100644
--- a/net/tunneldigger/Makefile
+++ b/net/tunneldigger/Makefile
@@ -1,9 +1,9 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=tunneldigger
-PKG_VERSION:=0.4.7
+PKG_VERSION:=0.4.8
 PKG_RELEASE:=1
-PKG_REV:=7cc92020cbafe5be2b24eb6bc943a65f151c2a18
+PKG_REV:=20e52a59180c4285aca932557f804bba08ce78b3
 
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.bz2
 PKG_SOURCE_URL:=git://github.com/wlanslovenija/tunneldigger.git
@@ -12,6 +12,7 @@ PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)
 PKG_SOURCE_VERSION:=$(PKG_REV)
 
 include $(INCLUDE_DIR)/package.mk
+include $(INCLUDE_DIR)/cmake.mk
 
 define Package/tunneldigger
   SECTION:=net
@@ -20,20 +21,14 @@ define Package/tunneldigger
   TITLE:=L2TPv3 tunnel broker client
 endef
 
-TARGET_CFLAGS += \
-	-I$(STAGING_DIR)/usr/include/libnl-tiny \
-	-I$(STAGING_DIR)/usr/include \
-	-DLIBNL_TINY
-
 define Build/Prepare
 	$(call Build/Prepare/Default)
 	mv $(PKG_BUILD_DIR)/client/* $(PKG_BUILD_DIR)
-	sed -i s/-lnl/-lnl-tiny/g $(PKG_BUILD_DIR)/Makefile
 endef
 
 define Package/tunneldigger/install
 	$(INSTALL_DIR) $(1)/usr/bin
-	$(INSTALL_BIN) $(PKG_BUILD_DIR)/l2tp_client $(1)/usr/bin/tunneldigger
+	$(INSTALL_BIN) $(PKG_BUILD_DIR)/tunneldigger $(1)/usr/bin/tunneldigger
 	$(INSTALL_DIR) $(1)/etc/init.d
 	$(INSTALL_BIN) ./files/tunneldigger.init $(1)/etc/init.d/tunneldigger
 	$(INSTALL_DIR) $(1)/etc/config
```

**Comment by RalfJung** [comment]
We have our [own version of the tunneldigger package](https://github.com/freifunk-saar/gluon-ffsaar/tree/master/ffsaar-tunneldigger) anway; I just copied the parts from your file that changed. Thanks :)

**Pull request merged**
