### PR TITLE
actually seed randomness if we use it

### PR DESCRIPTION
**Pull request by RalfJung**
Original patch by Peter J. Philipp, I adjusted it a bit.

### CODE REVIEW

**Review by mitar — APPROVED** [review]

**Comment by mitar** [comment]
BTW, on clients clock might not really be too random. Maybe we should seed randomness from some system device? At least there you can store entropy to preserve it across restarts.

**Comment by RalfJung** [comment]
I don't think it is very important that the broker selection uses cryptographic-strength randomness.^^

**Comment by mitar** [comment]
Oh, I am not talking about cryptographic-strength randomness. Only what happens if in some area electricity goes out, then comes back in, and then all nodes "randomly" pick the same server, because they have all same time. :-)

But sure. :-)

**Comment by RalfJung** [comment]
Fair.^^ That's why I used nanoseconds, I hoped those are sufficiently noisy...

**Pull request merged**
