### PR TITLE
Document how to find out the linux kernel version

### PR DESCRIPTION
**Pull request by niccokunzmann**
This lowers the threshold for beginners

### CODE REVIEW

**Comment by RalfJung** [comment]
Isn't `uname -v` a better suggestion? On Debian `-r` shows the Debian package version, `-v` the upstream version.

**Comment by RalfJung** [comment]
Also cycling PR to make CI re-run, looks like a spurious failure.

**Comment by kaechele** [comment]
Fedora:
```
[felix@x1 ~]$ uname -r
5.1.8-300.fc30.x86_64
[felix@x1 ~]$ uname -v
#1 SMP Sun Jun 9 17:09:32 UTC 2019

```
Ubuntu:
```
felix@ubuntu:~$ uname -r
5.0.0-13-generic
felix@ubuntu:~$ uname -v
#14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019
```

**Comment by RalfJung** [comment]
The Ubuntu thing doesn't exactly look like an upstream kernel version either. `5.0.0-13` is not a thing.

Debian:
```
$ uname -r
4.19.0-5-amd64
$ uname -v
#1 SMP Debian 4.19.37-3 (2019-05-15)
```
"4.19.37" is the actual upstream version.

Maybe just recommend `uname -a`?

**Comment by niccokunzmann** [comment]
I do not know if this is the case for you with the failing PRs: I had a configuration where it failed for external people without write access to the repository because the secrets if Travis did not resolve.

I pushed uname -a because that works for me, too and seems more universal

**Comment by RalfJung** [comment]
Oh wow, Travis is getting better every day. At producing ridiculous situations. Now even `git checkout $TRAVIS_COMMIT` is failing.

**Comment by niccokunzmann** [comment]
It does a checkout. https://travis-ci.org/wlanslovenija/tunneldigger/jobs/548248390#L436
Maybe it would be sufficient to print what the head commit is and what the pull request commit is. 
I also wondered: Fetching the commits from the "origin" may not allow fetching commits from my repository. So, I would not expect it to run.

Would it be ok if we just echo the current commit?

**Comment by RalfJung** [comment]
> Fetching the commits from the "origin" may not allow fetching commits from my repository.

GH integrates PR commit into the PR the PR is submitted to. You can even fetch them by querying the right ref: `git fetch origin pull/PRNUMBER/head`.

**Comment by RalfJung** [comment]
But I guess we'll just have to ignore `TRAVIS_COMMIT`, and instead query the top commit.

**Pull request merged**
