### PR TITLE
bump Ubuntu version we use on CI

### PR DESCRIPTION
**Pull request by RalfJung**
I'll use this PR to debug our CI problems.

@kaechele you mentioned already trying this an running into LXC issues. Do you have a branch for that? Also you suggested to use Vagrant instead for testing; that's fine for me but my Vagrant experience is about on the same level as my LXC experience (which is zero). We also have a [WIP docker image](https://github.com/wlanslovenija/tunneldigger/pull/99) that might help, maybe.

### CODE REVIEW

**Comment by kaechele** [comment]
I've done some testing here: https://travis-ci.org/kaechele/tunneldigger

The problem is with the newer Ubuntu versions that the cloning of the LXC container fails and the Python library for LXC has exactly zero error handling or logging. That's about how far I got.

**Comment by kaechele** [comment]
Okay. So I got as far as getting the LXC stuff somewhat working again: https://travis-ci.org/kaechele/tunneldigger/builds/601569731

But now we're facing issues with the older versions of the client not compiling due to errors thrown by the newer compiler.
Also there is no coverage for any Python 3 testing.

**Comment by RalfJung** [comment]
> But now we're facing issues with the older versions of the client not compiling due to errors thrown by the newer compiler.

That is odd; I am running this tunneldigger broker on several Debian Stretch servers just fine... which is newer than xenial.

>  Also there is no coverage for any Python 3 testing.

My rough plan was to first get CI work again with the old broker (Python 2 only), then make some kind of release or snapshot or so, and then move to Python 3 and drop Python 2 support. Supporting both at the same time does not seem worth the hassle, does it?

**Comment by RalfJung** [comment]
Yay, we have working CI again. :)

**Pull request merged**
