### PR TITLE
add wireshark lua dissector

### PR DESCRIPTION
**Pull request by lynxis**

### CODE REVIEW

**Comment by mitar** [comment]
Cam you document this file a bit? How to use it? What it is? Line comments?

**Comment by lynxis** [comment]
yes. I know. I'll add some documentation about how to use this file to the /docs/. I just want to publish it. because I written that thing 2 years ago.
a dissector parses a raw data network package. so when you sniff packages with wireshark, it shows you what kind of package this is. And it also forward the l2tp data packages to the l2tp parser, so you can even see all packges inside the tunnel.

**Comment by mitar** [comment]
This works both for the control and data packets?

**Comment by lynxis** [comment]
right.

**Comment by mitar** [comment]
Hm, I worry a bit how to assure we keep this parser in sync with any changes to the protocol. But probably we should not be changing the protocol much anyway. :-)

**Comment by kostko** [comment]
This should probably go into a separate directory?

**Comment by lynxis** [comment]
into which one? /docs/

**Comment by lynxis** [comment]
it's missing btw. the pmtu notify

**Comment by kostko** [comment]
Yes, I think `docs` should be ok.

**Comment by mitar** [comment]
Hm, can you still add documentation how to use it?

**Pull request merged**
