### PR TITLE
add .travis using tunneldigger-testing

### PR DESCRIPTION
**Pull request by lynxis**

### CODE REVIEW

**Comment by kostko** [comment]
Hm, perhaps we could bring the content of `tunneldigger-testing` directly into this repository under the `tests` directory?

**Comment by lynxis** [comment]
I had the same though. I'll extend this pr

**Comment by lynxis** [comment]
https://travis-ci.org/lynxis/tunneldigger/builds/93174240

**Comment by kostko** [comment]
There seem to be some references to the `testing` directory left, while it is `tests` now.

**Comment by lynxis** [comment]
fixed it.

**Comment by lynxis** [comment]
https://travis-ci.org/lynxis/tunneldigger/builds/93176595

/testing -> comes from the mounting point inside.

**Comment by lynxis** [comment]
do you already configured this repository for use in travis-ci?

**Comment by kostko** [comment]
Yes, a build has already been created, so let's see how it goes.

**Comment by kostko** [comment]
Check it out here:
* https://travis-ci.org/wlanslovenija/tunneldigger/builds/93183416

**Comment by mitar** [comment]
Thank you for this pull request! But now I noticed that you also changed the licensing of part of the code. I would really like to ask you if we could unify and simply this under the projects AGPL code? It is really strange that tests are licensed differently.

But based on all your contributions, I think it would be great to attribute you somehow as contributor. Maybe it is time to start a contributors list?

So, my question is, can I remove that dual-licensing file and simply make everything AGPL? What would be the way you would like to be attributed? What I am thinking is maybe a list of GitHub usernames and links to their GitHub profiles in README and documentation?

**Comment by lynxis** [comment]
Sorry, I did not pointed out that!

**Comment by mitar** [comment]
So, are you OK with what I am proposing?

**Comment by lynxis** [comment]
yes.

**Comment by mitar** [comment]
Thanks!

**Comment by mitar** [comment]
In tests README you are saying that you use python3, but in `.travis.yaml` you are using Python 2.7. Which one should it be then?

**Comment by mitar** [comment]
README talks about `test_td.py`, but I do not find this file anywhere?

**Comment by lynxis** [comment]
looks like I've to clean up the testing another time ;)

**Comment by lynxis** [comment]
it's py3

**Comment by mitar** [comment]
Sorry, I just try to make sense of things and keep them maintainable. :-)

**Pull request merged**
