### PR TITLE
check for data padding in CONTROL_TYPE_USAGE

### PR DESCRIPTION
**Pull request by RalfJung**
* [x] TODO before merging: Do some research to make sure that old clients also send this padding.

### CODE REVIEW

**Comment by RalfJung** [comment]
CI failure looks like some kind of network issue?
```
fatal: reference is not a tree: 186573e4c4f0b1cd3793901849fb6c5820dc0138

E

======================================================================

ERROR: test_usage.TestClientUsage.test_usage

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/home/travis/build/wlanslovenija/tunneldigger/tests/test_usage.py", line 31, in test_usage

    cont_client = tunneldigger.prepare('client', CONTEXT + '_usage_client', os.environ['CLIENT_REV'], bridge_name, '172.16.16.2/24')

  File "/home/travis/build/wlanslovenija/tunneldigger/tests/tunneldigger.py", line 187, in prepare

    raise RuntimeError('Failed to prepare the container "%s" type %s' % (name, cont_type))

nose.proxy.RuntimeError: Failed to prepare the container "e1622b6c_usage_client" type client
```

**Comment by kostko** [comment]
There seem to be some issues on Travis, I tried retrying the build but it just got stuck.

**Comment by RalfJung** [comment]
I checked both this repo's history and https://github.com/ffrl/tunneldigger, and in both cases, the usage message did this padding from the moment it was introduced. So I think it is safe to require it from all clients.

**Comment by kostko** [comment]
Can you push a new version to see if this will fix the Travis issues?

**Pull request merged**
