### PR TITLE
Better error and docs for our kernel requirements

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/wlanslovenija/tunneldigger/issues/129

### CODE REVIEW

**Comment by kaechele** [comment]
I'll deploy this today. I'm a little concerned with performance as we loop over every tunnel for each message we receive.

**Comment by RalfJung** [comment]
> I'll deploy this for testing today.

Thanks!

> I'm a little concerned with performance as we loop over every tunnel for each message we receive.

We only do that for messages we receive on the broker, i.e., for new clients. Messages that go to a tunnel socket don't get any checking.

**Comment by kaechele** [comment]
This has been running on one of our gateways in production now for the last week. No issues.
LGTM

**Comment by RalfJung** [comment]
Awesome, thanks for testing!

**Pull request merged**
