### PR TITLE
Describe check for netfilter

### PR DESCRIPTION
**Pull request by niccokunzmann**
fixes https://github.com/wlanslovenija/tunneldigger/issues/95

### CODE REVIEW

**Comment by kaechele** [comment]
This information is irrelevant.
L2TP was introduced in 2.6.23. The only reason you might not have netfilter enabled in any Kernel that would support tunneldigger is because you built it yourself and have it purposely disabled. If you did that you know all about it.

**Comment by RalfJung** [comment]
TBH it might be best to just remove most of that discussion of kernel modules, and assume a default configuration. AFAIK all distros have everything enabled we need. So even talking about this is just confusing.

**Comment by RalfJung** [comment]
Well okay we still need the part about loading them.

So maybe just tell people to create an `/etc/modules-load.d/tunneldigger.conf` containing
```
l2tp_core
l2tp_eth
l2tp_netlink
```

**Comment by niccokunzmann** [comment]
I see these lines in the .travis.yml:

https://github.com/wlanslovenija/tunneldigger/blob/8d4d2f9abeb2644e943e7f4babb885960aecb5d8/.travis.yml#L17
https://github.com/wlanslovenija/tunneldigger/blob/8d4d2f9abeb2644e943e7f4babb885960aecb5d8/.travis.yml#L18
I think they are enabled by default.

However, it might not hurt adding them next to the others of they are needed.

**Comment by RalfJung** [comment]
This is overlapping with https://github.com/wlanslovenija/tunneldigger/pull/94. I suggest to close this PR and do the netfilter edits there.

**Comment by niccokunzmann** [comment]
:+1:

**Pull request closed without merging**
