### PR TITLE
do not close connection immediately on EPOLLERR

### PR DESCRIPTION
**Pull request by RalfJung**
Hopefully fixes https://github.com/wlanslovenija/tunneldigger/issues/171

### CODE REVIEW

**Comment by pmelange** [comment]
Here are the logs I get with commit id 1a383570cadefe2c926dcf3d0a31d0f409cf1c5f

```
Wed Aug 16 16:40:30 2023 kern.info kernel: [515648.054051] br-digger1346: port 1(l2tp101-101) entered disabled state
Wed Aug 16 16:40:30 2023 kern.info kernel: [515648.054130] device l2tp101-101 entered promiscuous mode
Wed Aug 16 16:40:30 2023 kern.info kernel: [515648.054199] br-digger1346: port 1(l2tp101-101) entered blocking state
Wed Aug 16 16:40:30 2023 kern.info kernel: [515648.054201] br-digger1346: port 1(l2tp101-101) entered forwarding state
Wed Aug 16 16:40:33 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:35 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:38 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:40 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:42 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:44 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:47 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:49 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:52 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:56 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:40:59 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:41:03 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:41:06 2023 daemon.err python[10683]: [INFO/tunneldigger.tunnel] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): MTU set to 1396.
Wed Aug 16 16:41:06 2023 daemon.err python[10683]: [INFO/tunneldigger.hooks] Running hook 'session.mtu-changed' via script '/usr/lib/tunneldigger-broker/hooks/mtu-changed'.
Wed Aug 16 16:41:06 2023 kern.info kernel: [515683.860009] device l2tp100-100 left promiscuous mode
Wed Aug 16 16:41:06 2023 kern.info kernel: [515683.860033] br-digger1446: port 1(l2tp100-100) entered disabled state
Wed Aug 16 16:41:06 2023 daemon.notice netifd: bridge 'br-digger1446' link is down
Wed Aug 16 16:41:06 2023 daemon.notice netifd: Interface 'digger1446' has link connectivity loss
Wed Aug 16 16:41:06 2023 daemon.info olsrd[2611]: Removing interface br-digger1446
Wed Aug 16 16:41:06 2023 daemon.notice netifd: bridge 'br-digger1396' link is up
Wed Aug 16 16:41:06 2023 daemon.notice netifd: Interface 'digger1396' has link connectivity
Wed Aug 16 16:41:06 2023 daemon.info olsrd[2611]: Writing '0' (was 0) to /proc/sys/net/ipv4/conf/br-digger1396/send_redirects
Wed Aug 16 16:41:06 2023 daemon.info olsrd[2611]: Writing '0' (was 0) to /proc/sys/net/ipv4/conf/br-digger1396/rp_filter
Wed Aug 16 16:41:06 2023 daemon.info olsrd[2611]: Adding interface br-digger1396
```

**Comment by pmelange** [comment]
Those log messages keep on coming.  It's spamming the log file
```
Wed Aug 16 16:52:03 2023 authpriv.info dropbear[10836]: Child connection from 161.35.114.58:49250
Wed Aug 16 16:52:03 2023 authpriv.warn dropbear[10836]: Login attempt for nonexistent user
Wed Aug 16 16:52:03 2023 authpriv.info dropbear[10836]: Exit before auth from <161.35.114.58:49250>: Exited normally
Wed Aug 16 16:52:16 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:20 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:22 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:26 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:28 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:30 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:34 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:38 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:40 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:42 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:45 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:52:49 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 16:55:00 2023 cron.err crond[3498]: USER root pid 10837 cmd killall -HUP dnsmasq
Wed Aug 16 16:55:00 2023 daemon.info dnsmasq[1]: read /etc/hosts - 4 addresses
Wed Aug 16 16:55:00 2023 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 5 addresses
Wed Aug 16 16:55:00 2023 daemon.info dnsmasq[1]: read /tmp/hosts/olsr - 1339 addresses
Wed Aug 16 16:55:00 2023 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Wed Aug 16 16:56:37 2023 authpriv.info dropbear[10838]: Child connection from 161.35.114.58:46856
Wed Aug 16 16:56:38 2023 authpriv.info dropbear[10838]: Exit before auth from <161.35.114.58:46856>: (user 'root', 0 fails): Exited normally
Wed Aug 16 17:00:00 2023 cron.err crond[3498]: USER root pid 10847 cmd killall -HUP dnsmasq
Wed Aug 16 17:00:00 2023 daemon.info dnsmasq[1]: read /etc/hosts - 4 addresses
Wed Aug 16 17:00:00 2023 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 5 addresses
Wed Aug 16 17:00:00 2023 daemon.info dnsmasq[1]: read /tmp/hosts/olsr - 1339 addresses
Wed Aug 16 17:00:00 2023 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Wed Aug 16 17:00:00 2023 daemon.info dnsmasq[1]: read /etc/hosts - 4 addresses
Wed Aug 16 17:00:00 2023 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 5 addresses
Wed Aug 16 17:00:00 2023 daemon.info dnsmasq[1]: read /tmp/hosts/olsr - 1339 addresses
Wed Aug 16 17:00:00 2023 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Wed Aug 16 17:01:14 2023 authpriv.info dropbear[10848]: Child connection from 161.35.114.58:47510
Wed Aug 16 17:01:14 2023 authpriv.warn dropbear[10848]: Login attempt for nonexistent user
Wed Aug 16 17:01:14 2023 authpriv.info dropbear[10848]: Exit before auth from <161.35.114.58:47510>: Exited normally
Wed Aug 16 17:04:00 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:04 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:08 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:11 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:14 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:18 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:21 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:23 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:27 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:30 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:34 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:04:36 2023 daemon.err python[10683]: [WARNING/tunneldigger.network] Tunnel 100 (b6:e5:b7:75:f8:b4:6d:3d:9f:41): error reading from socket: [Errno 90] Message too large
Wed Aug 16 17:05:00 2023 cron.err crond[3498]: USER root pid 10850 cmd killall -HUP dnsmasq
Wed Aug 16 17:05:00 2023 cron.err crond[3498]: USER root pid 10851 cmd test -e /usr/sbin/owm.sh && /usr/sbin/owm.sh
Wed Aug 16 17:05:00 2023 daemon.info dnsmasq[1]: read /etc/hosts - 4 addresses
Wed Aug 16 17:05:00 2023 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 5 addresses
Wed Aug 16 17:05:00 2023 daemon.info dnsmasq[1]: read /tmp/hosts/olsr - 1339 addresses
```

**Comment by RalfJung** [comment]
Ah so it is even a different error code, "Message too large"... I'm getting tons of these
```
[WARNING/tunneldigger.network] Tunnel 194 (14cc20b4c792): error reading from socket: [Errno 111] Connection refused
```
I'm not sure if we even still need the error_count logic. Probably the thing that lead to #143 is that we *didn't* do the read, and then it just kept telling us that there is an error waiting to be fetched. So the resolution is to always read after you got an error... if the connection is truly dead, it will time out.

> It would be nice if it didn't take 30 secs to do the mtu change.

https://github.com/wlanslovenija/tunneldigger/pull/183 could help, but without client logs it's hard to say what the slow part is. Anyway let's stay on topic please. :)

> Those log messages keep on coming. It's spamming the log file

Yes that is expected. PMTU discovery is repeated every few minutes, and each time it will try to send these big packets (because maybe something changed about the connection and now they work), and then it will get errors because it failed to send the big packets. The interval should be 10min on average so it shouldn't spam the log file too much.

**Comment by RalfJung** [comment]
Okay the latest version should silence these new errors. I also rebased so the branch now includes the hopefully faster PMTU discovery. Can you try that?

**Comment by pmelange** [comment]
It seems to be working a lot better.  And the mtu discovery is happening a lot sooner, which is excellent.  Smooth!

**Comment by RalfJung** [comment]
Great, thanks for testing!

I've deployed this to 2 of our servers as well and don't see any problems there either. We still have some clients struggling but I don't think that is our fault... they just randomly reject a bunch of our UDP packets for some reason.

So... I think we can go ahead and land this. :)

**Pull request merged**
